name: schulapp
description: "A new Flutter project."
publish_to: "none"
version: 0.10.2+27 #v.v.v+versionForGooglePlayStore

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  archive: ^4.0.7
  flutter_colorpicker: ^1.1.0
  flutter_speed_dial: ^7.0.0
  go_router: ^16.2.1 #https://www.youtube.com/watch?v=b6Z885Z46cU
  google_fonts: ^6.2.1
  path: ^1.8.3
  path_provider: ^2.1.1
  file_picker: ^10.3.3
  animated_list_plus: ^0.5.2
  flutter_local_notifications: ^19.2.1
  timezone: ^0.10.0
  permission_handler: ^12.0.1
  tuple: ^2.0.2
  shared_preferences: ^2.2.2
  fl_chart: ^1.1.0
  flutter_localizations:
    sdk: flutter
  intl: any
  package_info_plus: ^8.0.0
  home_widget: ^0.8.0
  change_app_package_name: ^1.3.0
  # receive_sharing_intent: ^1.8.0
  encrypt: ^5.0.3
  http: ^1.2.2
  pdfrx: ^2.1.12
  image_picker: ^1.1.2
  image: ^4.3.0
  open_file: ^3.5.8
  share_plus: ^11.1.0
  url_launcher: ^6.3.1
  flutter_image_clipboard: ^1.0.0
  feedback: ^3.1.0
  in_app_review: ^2.0.10
  table_calendar: ^3.1.3
  msix: ^3.16.9
  mobile_scanner: ^7.0.1
  qr_flutter: ^4.1.0
  extension_google_sign_in_as_googleapis_auth: ^3.0.0
  googleapis: ^14.0.0
  uuid: ^4.5.1
  google_sign_in_all_platforms: ^2.0.2

  # fluent_ui: ^4.8.1
  # flutter_acrylic: ^1.1.3 #Window acrylic, mica & transparency effects for Flutter on Windows, macOS & Linux
  # provider: ^6.1.1
  # system_theme: ^2.3.1 #A flutter plugin to get the current system theme information
  # window_manager: ^0.3.7 #This plugin allows Flutter desktop apps to resizing and repositioning the window.

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  generate: true

msix_config:
  display_name: Schulapp
  identity_name: com.flologames.schulapp
  msix_version: 0.0.9.8
  store: false
  install_certificate: false
  output_name: schulapp-installer
  toast_activator:
    clsid: "4a9f4a94-8f00-4cc5-a82d-20187c1a4240"
    arguments: "msix-args"
    display_name: "Schulapp"

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon.png"
  adaptive_icon_background: "#ffffff"  
  adaptive_icon_foreground: "assets/icon.png" 
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/icon.png"
    background_color: "#1c1b1f"
    theme_color: "#25232a"
  windows:
    generate: true
    image_path: "assets/icon_win.png"
    icon_size: 256 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "assets/icon.png"
